import './globals.css'

import localFont from 'next/font/local'

import { StoreProvider } from '@/Providers/StoreProvider'

const myFont = localFont({
  src: [
    {
      path: '../../public/fonts/light.ttf',
      weight: '300',
      style: 'medium',
    },
    {
      path: '../../public/fonts/regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../../public/fonts/semibold.ttf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: '../../public/fonts/bold.ttf',
      weight: '700',
      style: 'bold',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
